### ISSUE TITLE
Not working in iOS 9

### ISSUE THREAD

**Issue by iamabhiee** [googlemaps/OpenInGoogleMaps-iOS#3]
With iOS 9 its not redirecting to google maps anymore

**Comment by iamabhiee** [comment]
From Log : 

canOpenURL: failed for URL: "comgooglemaps-x-callback://" - error: "This app is not allowed to query for scheme comgooglemaps-x-callback"

**Comment by ToddKerpelman** [comment]
This is due to a new security feature in iOS9 -- Apps cannot call `canOpenURL` unless you explicitly add the custom URL scheme to a "LSApplicationQueriesSchemes" array in your info.plist file. (Check out [this link](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/index.html#//apple_ref/occ/instm/UIApplication/canOpenURL:) for more information.)

To get the current library working in iOS 9, you'll want to add support for `comgooglemaps`, `comgooglemaps-x-callback`, and your App's own custom URL scheme. I've updated the sample so you can see how it works.

That said, I don't know what the Google Maps team is planning around Universal Link support for iOS -- if they add that, there's a good chance this library will change significantly to support Universal Links instead, which would obviate the need for this fix. 

But for now, add the fix. I'll updated the readme file, too, to reflect this.
